branch-defaults:
  master:
    environment: retreat-temp-dev
    group_suffix: null
global:
  application_name: retreat-temp
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: PHP 5.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: personal
  repository: null
  sc: git
  workspace_type: Application
